services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../obscura_backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env.production
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PHOTO_UPLOAD_DIR: ${PHOTO_UPLOAD_DIR}
    volumes:
      - ./uploads:/uploads
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../obscura_frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file: .env.production
    environment:
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
